package model;

import java.util.List;

/**
 * Represents a movie with detailed information, including title, rating, genres, and more.
 * Provides methods to access movie details.
 *
 * @author Erdun E
 * @version 1.35
 * @since 2024-12-10
 * Course: CS5010 Program Design Paradigm
 * Program: Final Project
 */
public class Movie {
    private final String title;
    private final List<String> genres;
    private final double rating;
    private final String overview;
    private final String posterPath;
    private final String director;
    private final String releaseDate;
    private final int releaseYear;
    private final String duration;
    private final String ratingLevel;
    private final List<String> keywords;
    private final List<String> cast;
    private final long revenue;
    private String language;
    private String trailerUrl;

    /**
     * Constructs a new Movie object with the specified details.
     *
     * @param title       The title of the movie.
     * @param posterPath  The path to the poster image.
     * @param rating      The rating of the movie.
     * @param genres      The list of genres associated with the movie.
     * @param overview    A brief description of the movie.
     * @param director    The director of the movie.
     * @param releaseDate The release date of the movie.
     * @param releaseYear The release year of the movie.
     * @param duration    The duration of the movie.
     * @param ratingLevel The rating level (e.g., PG, R).
     * @param language    The language of the movie.
     * @param keywords    The list of keywords related to the movie.
     * @param cast        The list of main cast members.
     * @param revenue     The revenue generated by the movie.
     */
    public Movie(String title, String posterPath, double rating, List<String> genres, String overview,
                 String director, String releaseDate, int releaseYear, String duration, String ratingLevel,
                 String language, List<String> keywords, List<String> cast, long revenue) {
        this.title = title;
        this.posterPath = posterPath != null ? posterPath : "";
        this.rating = rating;
        this.genres = genres;
        this.overview = overview;
        this.director = director;
        this.releaseDate = releaseDate;
        this.releaseYear = releaseYear;
        this.duration = duration;
        this.ratingLevel = ratingLevel;
        this.language = language;
        this.keywords = keywords;
        this.cast = cast;
        this.revenue = revenue;
    }

    /**
     * Gets the movie title.
     *
     * @return The title of the movie.
     */
    public String getTitle() {
        return title;
    }

    /**
     * Gets the list of genres.
     *
     * @return A list of genres.
     */
    public List<String> getGenres() {
        return genres;
    }

    /**
     * Gets the movie rating.
     *
     * @return The rating of the movie.
     */
    public double getRating() {
        return rating;
    }

    /**
     * Gets the movie overview.
     *
     * @return A brief description of the movie.
     */
    public String getOverview() {
        return overview;
    }

    /**
     * Gets the URL to the movie poster.
     *
     * @return The full URL to the poster image.
     */
    public String getPosterUrl() {
        return "https://image.tmdb.org/t/p/w200" + posterPath;
    }

    /**
     * Gets the movie director.
     *
     * @return The director's name.
     */
    public String getDirector() {
        return director;
    }

    /**
     * Gets the release date of the movie.
     *
     * @return The release date in string format.
     */
    public String getReleaseDate() {
        return releaseDate;
    }

    /**
     * Gets the release year of the movie.
     *
     * @return The release year as an integer.
     */
    public int getReleaseYear() {
        return releaseYear;
    }

    /**
     * Gets the movie duration.
     *
     * @return The duration of the movie.
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Gets the rating level.
     *
     * @return The rating level.
     */
    public String getRatingLevel() {
        return ratingLevel;
    }

    /**
     * Gets the movie language.
     *
     * @return The language of the movie.
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the movie language.
     *
     * @param language The language to set.
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * Gets the list of keywords related to the movie.
     *
     * @return A list of keywords.
     */
    public List<String> getKeywords() {
        return keywords;
    }

    /**
     * Gets the list of main cast members.
     *
     * @return A list of cast members.
     */
    public List<String> getCast() {
        return cast;
    }

    /**
     * Gets the trailer URL.
     *
     * @return The trailer URL.
     */
    public String getTrailerUrl() {
        return trailerUrl;
    }

    /**
     * Sets the trailer URL.
     *
     * @param trailerUrl The trailer URL to set.
     */
    public void setTrailerUrl(String trailerUrl) {
        this.trailerUrl = trailerUrl;
    }

    /**
     * Gets the movie revenue.
     *
     * @return The formatted revenue or "NO UPDATE" if revenue is not available.
     */
    public String getRevenue() {
        return revenue > 0 ? String.format("$%,d", revenue) : "NO UPDATE";
    }
}